deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_XXXX }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'hughigh-app-frontend'
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_XXXX }}
